volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - DB_HOST=localhost
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=pass
    restart: always
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/backend/media/

  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles/
      - media:/backend/media/