# Generated by Django 5.2.5 on 2025-09-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="full_price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
