# Generated by Django 5.2.5 on 2025-09-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_service_full_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
