# Generated by Django 5.2.5 on 2025-09-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_subscription_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="comment",
            field=models.CharField(blank=True, default="", null=True),
        ),
    ]
